name: deploy

on:
  pull_request:
    types:
      - closed
    branch:
      - develop

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Deploy 
      run: |
        git pull origin develop
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        systemctl restart ${{ secrets.REDDIFY_SERVICE }}
      working-directory: ${{ secrets.REDDIFY_PATH }}