name: deploy

on:
  push:
    branch:
      - develop

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Deploy 
      run: |
        cp -r . ${REDDIFY_PATH}
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        systemctl restart ${REDDIFY_SERVICE}